### ISSUE TITLE
Authentication: choosing an LDAP server dynamically

### ISSUE THREAD

**Issue by mbyta** [DarwinOnLine/DoLLdapBundle#1]
Hi @DarwinOnLine,
Great bundle you have here.

My problem is this: on the login screen, the user selects his company; I want the application to select directly the corresponding LDAP server for authenticating that user.
I don't want it to loop over all the existing servers untill it finds the actual server.

How can I configure your bundle in order to achieve this ?

Thanks !!

**Comment by DarwinOnLine** [comment]
Hello @mbyta, actually you can't select only one LDAP server to authenticate your user.
You can open a PR to permit it, I have no time actually to do it :(

**Comment by mbyta** [comment]
Got it !

Thanks for your answer !
