### ISSUE TITLE
[new feature?] Retrieving all users with their groups from a domain

### ISSUE THREAD

**Issue by sergionegri** [DarwinOnLine/DoLLdapBundle#3]
Apart from the authentication side, it would be great for us having the possibility of retrieving all users with their groups. Can this be done out of the box or does it require some addition to the bundle?

Thank you

**Comment by DarwinOnLine** [comment]
Hello @sergionegri, you can use the `dol_ldap.ldap_driver` service to search all users :
```php
$driver = $this->get('dol_ldap.ldap_driver');
$driver->init($this->getParameter('dol_ldap.domains.parameters')['server1']['driver']);
$allUsers = $driver->search('ou=users,dc=host,dc=foo'), '(&(ObjectClass=Person))');
```

But you can directly use the [ZendLdap library](https://github.com/zendframework/zend-ldap) to do that. My bundle is first thought for authentication :)
