### ISSUE TITLE
[documentation] how to specify authenticating against server1/server2 or skipping LDAP

### ISSUE THREAD

**Issue by sergionegri** [DarwinOnLine/DoLLdapBundle#4]
We'd like to integrate our SaaS with LDAP/AD.

Being a SaaS we'll have several clients with different servers (and some with no LDAP). How do we define when authenticating against server1, when server2 and when skipping LDAP/AD authentication altogether?

**Comment by DarwinOnLine** [comment]
You should use a [chain provider](https://symfony.com/doc/current/security/multiple_user_providers.html), using the DoLLdapBundle and your authentication logic with your servers without LDAP.

See [this example](https://github.com/DarwinOnLine/DoLLdapBundle/blob/master/Resources/doc/index.md#5-enable-fosuserbundle-as-user-provider) in the documentation.
